name: CI Tests

on: push

jobs:
  lint-design-system:
    name: Lint design-system package
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/design-system
    steps:
      - uses: actions/checkout@v2
      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org
          scope: "@recidiviz"
      - name: Yarn install with cache
        uses: bahmutov/npm-install@v1
        with:
          working-directory: packages/design-system
          install-command: yarn --frozen-lockfile
      - name: Yarn lint
        run: yarn lint
  # We want to make sure we're always able to build our artifacts.
  build-design-system:
    name: Build design-system package
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/design-system
    steps:
      - uses: actions/checkout@v2
      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org
          scope: "@recidiviz"
      - name: Yarn install with cache
        uses: bahmutov/npm-install@v1
        with:
          working-directory: packages/design-system
          install-command: yarn --frozen-lockfile
      - name: Yarn build
        run: yarn build
  lint-test-auth:
    name: Lint and test auth package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # This clones the repo and checks out the SHA that triggered this action.
          # We set fetch-depth 0 to fetch all branches and history so that merge-base
          # is guaranteed to be able to find the common ancestor with the base branch.
          # See https://github.com/actions/checkout#readme
          fetch-depth: 0
      - name: Yarn caching
        uses: actions/cache@v2
        id: yarn-caching
        with:
          path: "**/node_modules"
          key: yarn-v2-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-v2-${{ hashFiles('**/yarn.lock') }}
            yarn-v2-
            yarn-
      - name: Yarn install
        if: steps.yarn-caching.outputs.cache-hit != 'true'
        working-directory: packages/auth
        run: yarn install --frozen-lockfile
      - name: Yarn lint
        working-directory: packages/auth
        run: yarn lint
      - name: Yarn test
        working-directory: packages/auth
        run: yarn test
