name: Publish tagged packages

on:
  release:
    types: [published]

jobs:
  publish-eslint-config:
    name: Publish eslint-config package
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/eslint-config@') }}
    defaults:
      run:
        working-directory: packages/eslint-config
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: Use Node 14
        uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # v1.4.6
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org
          scope: "@recidiviz"
      - name: Yarn install with cache
        uses: bahmutov/npm-install@6bbff949458c1dd99b20e185cee8c4d6fcf1212a # v1.10.9
        with:
          working-directory: packages/eslint-config
          install-command: yarn --frozen-lockfile
      - name: Publish
        run: npm publish --verbose --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  publish-tsconfig:
    name: Publish tsconfig package
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/tsconfig@') }}
    defaults:
      run:
        working-directory: packages/tsconfig
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: Use Node 14
        uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # v1.4.6
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org
          scope: "@recidiviz"
      - name: Publish
        run: npm publish --verbose --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  publish-design-system:
    name: Publish design-system package
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/design-system@') }}
    defaults:
      run:
        working-directory: packages/design-system
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: Use Node 14
        uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # v1.4.6
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org
          scope: "@recidiviz"
      - name: Yarn install with cache
        uses: bahmutov/npm-install@6bbff949458c1dd99b20e185cee8c4d6fcf1212a # v1.10.9
        with:
          working-directory: packages/design-system
          install-command: yarn --frozen-lockfile
      - name: Yarn build
        run: yarn build
      - name: Publish
        run: npm publish --verbose --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Deploy Storybook
        run: yarn run deploy-storybook
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
  publish-auth:
    name: Publish auth package
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/auth@') }}
    defaults:
      run:
        working-directory: packages/auth
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: Use Node 14
        uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # v1.4.6
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org
          scope: "@recidiviz"
      - name: Yarn install with cache
        uses: bahmutov/npm-install@6bbff949458c1dd99b20e185cee8c4d6fcf1212a # v1.10.9
        with:
          working-directory: packages/auth
          install-command: yarn --frozen-lockfile
      - name: Yarn build
        run: yarn build
      - name: Publish
        run: npm publish --verbose --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
